name: github-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: composer install
        run: make install
      - name: run linter
        run: make lint
      - name: setup
        run: make setup
      - name: run tests
        run: make test
      - name: run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true